/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CheckboxIonic {
    }
    interface MyApp {
    }
    interface MyCheckbox {
        "checked": boolean;
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLCheckboxIonicElement extends Components.CheckboxIonic, HTMLStencilElement {
    }
    var HTMLCheckboxIonicElement: {
        prototype: HTMLCheckboxIonicElement;
        new (): HTMLCheckboxIonicElement;
    };
    interface HTMLMyAppElement extends Components.MyApp, HTMLStencilElement {
    }
    var HTMLMyAppElement: {
        prototype: HTMLMyAppElement;
        new (): HTMLMyAppElement;
    };
    interface HTMLMyCheckboxElement extends Components.MyCheckbox, HTMLStencilElement {
    }
    var HTMLMyCheckboxElement: {
        prototype: HTMLMyCheckboxElement;
        new (): HTMLMyCheckboxElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "checkbox-ionic": HTMLCheckboxIonicElement;
        "my-app": HTMLMyAppElement;
        "my-checkbox": HTMLMyCheckboxElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CheckboxIonic {
    }
    interface MyApp {
    }
    interface MyCheckbox {
        "checked"?: boolean;
    }
    interface MyComponent {
        "onButtonClicked"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "checkbox-ionic": CheckboxIonic;
        "my-app": MyApp;
        "my-checkbox": MyCheckbox;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "checkbox-ionic": LocalJSX.CheckboxIonic & JSXBase.HTMLAttributes<HTMLCheckboxIonicElement>;
            "my-app": LocalJSX.MyApp & JSXBase.HTMLAttributes<HTMLMyAppElement>;
            "my-checkbox": LocalJSX.MyCheckbox & JSXBase.HTMLAttributes<HTMLMyCheckboxElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
